### PR TITLE
Make use of telemetry configuration by sending key metrics.

### LINKED ISSUE #67: Make use of telemetry configuration by sending key metrics
**Description**

Currently replicator has a configuration section for telemetry, but does not send any useful metrics from events during the applications lifecycle. Replicator should be configured to send a number of key metrics including gauges about scaling triggers etc.

### PR DESCRIPTION
**Pull request by jrasell**
This commit introduces initial metrics which will help debug and
understand Replicator performance. The telemetry configuration
setup has also been updated to allow future additional endpoints
as well as sending the USR1 signal to output metrics to the stderr
log.

Closes #67

### CODE REVIEW

**Comment by jrasell** [comment]
Once the change is merged, the following will be added to the Replicator wiki:

# Telemetry

Replicator collects various metrics which can be used as information to understand and get a better view of what and how replicator is performing. To view the metrics you can either configure the StatsD telemetry endpoint and view metrics through your selected dash-boarding application or send the Replicator process the USR1 signal. When the USR1 signal is sent to Replicator it will dump metrics to the stderr log.

The exposed metrics are categorized below and Replicators default telemetry interval is 10 seconds.

## Runtime Telemetry
| Metric                               | Description | Type    | Measurement |
|--------------------------------------|-------------|---------|-------------|
| replicator.runtime.alloc_bytes       | This measures the number of bytes allocated by the Replicator process. | gauge | # allocated bytes |
| replicator.runtime.free_count        | This measures the cumulative count of heap objects freed. | gauge | total # freed objects |
| replicator.runtime.heap_objects      | This measures the number of objects allocated on the heap and is a general memory pressure indicator. | gauge | # allocation objects |
| replicator.runtime.malloc_count      | This measure the cumulative count of heap objects allocated by replicator. | guage | total # allocation heap objects |
| replicator.runtime.num_goroutines    | This tracks the number of running goroutines and is a general load pressure indicator. | gauge | # go routines |
| replicator.runtime.sys_bytes         | This measures the virtual address space reserved by the Replicator for the heap, stacks, and other internal data structures. | gauge | # systems bytes |
| replicator.runtime.total_gc_pause_ns | This is the cumulative nanoseconds in GC stop-the-world pauses since the program started. | gauge | total ns GC pause |
| replicator.runtime.gc_runs           | This tracks the number of completed GC cycles. | gauge | # GC cycles |


## Cluster Scaling Telemetry
| Metric                                       | Description | Type    | Measurement |
|----------------------------------------------|-------------|---------|-------------|
| replicator.cluster.aws.scale_out             | This increments every time the AWS activities related to a scaling-out event has been completed. | counter | events |
| replicator.cluster.aws.scale_in              | This increments every time the AWS activities related to a scaling-in event has been completed. | counter | events |
| replicator.cluster.aws.instance_terminations | This increments when an AWS instance is terminated and confirmed in the state "terminated". | counter | events |
| replicator.cluster.scale_out_failed          | This is incremented when a new node fails to join the cluster after a certain threshold of the instance being confirmed running. | counter | events |
| replicator.cluster.scale_out_success         | This represents the completion of a full scale-out event with the new node confirmed in the cluster worker pool. | counter | events |
| replicator.cluster.scaling_disabled          | This represents a situation where Replicator has suspended cluster scaling due to failed scale-outs. | counter | events |

## Job Scaling Telemetry
| Metric                                       | Description | Type    | Measurement |
|----------------------------------------------|-------------|---------|--------------
| replicator.job.<job_name>.<group_name>.scale_out | This increments when a Nomad job-group is scaled out and tracks the scale-out events.| counter | events |
| replicator.job.<job_name>.<group_name>.scale_in  | This increments when a Nomad job-group is scaled in and tracks the scale-in events. | counter | events |
| replicator.job.config_read                       | This tracks the time it takes replicator to read job scaling documents from Consul KV. | timer | ms/config read |

**Comment by jippi** [comment]
any plan to have tagged metrics ? 

so  `replicator.job.<job_name>.<group_name>.scale_out` would be 

`replicator.job.scale_out` with tags `job_name=<job_name>;group_name=<group_name>` - for datadog, influxdb etc

**Comment by ericwestfall** [comment]
As discussed, might be cool to structure this like the `logging` and `notifier` packages in the future and implement standard interfaces so we can support other providers but this looks absolutely lovely :-)

**Comment by jrasell** [comment]
@jippi it hadn't been something that we considered, primarily because I have not worked with either datadog or influxdb. If you could open a ticket with the relevant information it would be appriciated and we can certainly take a look into it when the time is right. It would likely involve rewriting the telemetry into a factory method pattern as @ericwestfall mentioned above.

**Pull request merged**
